### PR TITLE
fix: revert "chore(deps): Bump the production-dependencies group with 3 up…

### PR DESCRIPTION
**Pull request by guilhem-barthes**
…dates (#455)"

This reverts commit a192ea1cdbc43be1a241514af1537f5adef986de.

## Checklist

- [ ] [changelog](../CHANGELOG.md) was updated with notable changes
- [ ] documentation was updated

### CODE REVIEW

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by guilhem-barthes** [comment]
/e2e --tests sdk,substrafl,frontend,mnist,camelyon,doc --refs=substra-frontend=fix/revert-chakra-to-2.6.1

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Pull request closed without merging**
