### PR TITLE
chore: remove `distributed` skaffold profile and `chaincode*` images

### PR DESCRIPTION
**Pull request by thbcmlowk**
# Issue

FL-1237

# Description

* Removed `distributed` Skaffold profile and mentions in `README.md`
* Removed `chaincode-init` and `chaincode` docker images and workflows

## Checklist

- [x] [changelog](../CHANGELOG.md) was updated with notable changes
- [x] documentation was updated

## Needs

https://github.com/owkin/substra-ci/pull/133
https://github.com/Substra/substra-documentation/pull/379

## Related 

https://github.com/Substra/substra-backend/pull/768

### CODE REVIEW

**Review by SdgJlbl — APPROVED** [review]

**Comment by Owlfred** [comment]
Something happened while processing your message: Unexpected inputs provided: ["orchestratorMode"]

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Review by guilhem-barthes — APPROVED** [review]
LGTM

**Pull request merged**
