### PR TITLE
fix: function action propagation

### PR DESCRIPTION
**Pull request by guilhem-barthes**
## Description

Fixes FL-1426

## Checklist

- [ ] [changelog](../CHANGELOG.md) was updated with notable changes
- [ ] documentation was updated

### CODE REVIEW

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Review by SdgJlbl — COMMENTED** [review]
Do we want to add the test case that was not previously covered somewhere? (I'm not sure where)
Namely, the function fails and the function owner is not the task owner

**Review by SdgJlbl — APPROVED** [review]
Thanks

**Pull request merged**
