### PR TITLE
chore: remove mode flag

### PR DESCRIPTION
**Pull request by guilhem-barthes**
## Description

Remove the last references of the orchestrator mode

Closes FL-1331

## Checklist

- [ ] [changelog](../CHANGELOG.md) was updated with notable changes
- [ ] documentation was updated

### CODE REVIEW

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Review by ThibaultFy — APPROVED** [review]
Don't forget to update the changelog :) 
Thanks for the PR !

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Pull request merged**
